version: '{build}'

image: Visual Studio 2019
configuration:
  - Release
environment:
  PYTHON: C:\Python37-x64
  VSINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
install:
  - cmd: |
      curl -LO https://aka.ms/vs/16/release/vs_community.exe
      vs_community.exe modify --installPath "%VSINSTALLDIR%" --add Microsoft.VisualStudio.Workload.Python --quiet --wait
      set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
      python --version
      python -m pip install -U pip
      python -m pip install -r ManualGenerator\requirements.txt

before_build:
  - cmd: nuget restore
build:
  parallel: true
  verbosity: minimal
after_build:
  - cmd: CollectArtifacts.bat %CONFIGURATION%

artifacts:
  - path: publish
    name: threplay_rpi

deploy:
  provider: GitHub
  auth_token:
    secure: XBLZ1KuCOmvayGOFMZwYC+QyZxCmr0og6vKt53trP9I3WgF77pN+aVZvim2UP2Dm
  description: ''
  on:
    appveyor_repo_tag: true
